### ISSUE TITLE
Docker container does not work due to Python v3 incompatibility

### ISSUE THREAD

**Issue by jurajama** [vmware/vcd-cli#107]
I have successfully built a Docker container from Dockerfile.dev using tag 19.2.1, but "vca" command does not work in the container. This is because the container is built based on "python:3", but pyvcloud module is not compatible with Python v3 due to StringIO module whose usage has changed in Python 3.0, see for example https://stackoverflow.com/questions/11914472/stringio-in-python3

So either the container needs to be modified to use Python v2, or pyvcloud made compatible with Python v3.

```Docker container does not work due to Python v3 incompatibility
root@2ff82e14a0a1:~/vcd-cli# vca
Traceback (most recent call last):
  File "/usr/local/bin/vca", line 6, in <module>
    from vca_cli.vca_cli import cli
  File "/root/vcd-cli/vca_cli/vca_cli.py", line 16, in <module>
    from vca_cli.cmd_proc import CmdProc
  File "/root/vcd-cli/vca_cli/cmd_proc.py", line 22, in <module>
    from pyvcloud.vcloudair import VCA
  File "/usr/local/lib/python3.6/site-packages/pyvcloud/vcloudair.py", line 31, in <module>
    from StringIO import StringIO
ModuleNotFoundError: No module named 'StringIO'
```

**Comment by pacogomez** [comment]
we are deprecating `vca` command and moving to `vcd` command, which is based on Python 3.

**Comment by jurajama** [comment]
Ok thanks for clarification. This guidance directed me to using `vcd` command and that works ok so this issue can be closed.
