### ISSUE TITLE
Verbose output for login failures

### ISSUE THREAD

**Issue by ajlanghorn** [vmware/vcd-cli#11]
When authentication to a vCloud Director instance fails, the only output returned to `stdout` is "login failed", per [vca_cli.py#L253](https://github.com/vmware/vca-cli/blob/master/vca_cli/vca_cli.py#L253). It would be good to have verbose output available in order that the failure is more obvious.

I'll take a look at looking through the code at some point in future to see if I can fix this.

**Comment by tthayer** [comment]
I added the following to /usr/local/bin/vca to help debug my login issues:
`
import logging
import httplib
httplib.HTTPConnection.debuglevel = 1
logging.basicConfig()
logging.getLogger().setLevel(logging.DEBUG)
requests_log = logging.getLogger("requests.packages.urllib3")
requests_log.setLevel(logging.DEBUG)
requests_log.propagate = True
`

**Comment by greeneg** [comment]
With v15, I'm seeing "Can't login: Access is forbidden', however I can login fine from the web UI of our vCloud Director instance. The command line I'm using follows:

vca --insecure login Administrator --host alv-vcloud-director.minervanetworks.com --version 5.5

I'm not getting any extra error output when adding the -d flag, making determining what is causing this difficult....

**Comment by zoquero** [comment]
Hi!
Is this issue solved? I have a similar issue. Has anybody being able to login to vCloud Director 5.5 standalone?
Thanks and best regards,
/Ángel
