### ISSUE TITLE
Command line errors change the colour of the terminal

### ISSUE THREAD

**Issue by dsaojose** [vmware/vcd-cli#115]
**Steps**
1. Run any command that reliably produces a failure.

**Observation**
- The prompt is now black.
- The typed text is now black.
- I am unable to read my text when using a black background.

**Expectation**
- When the command fails, I expect that my console colours do not change.

**Workaround**
- Running the `tput init` command resets the colours of the console.

**Comment by rocknes** [comment]
Issue has been fixed with commit e351286
