### ISSUE TITLE
create vdc, edge, and org vdc network

### ISSUE THREAD

**Issue by flamby** [vmware/vcd-cli#140]
Hi,
I guess it's under developement, I see a ```create_org```, but for instance no create vdc.
I had a look at the ```create_org``` function to mimick it for ```create_vdc```, but it does its magic it seems thanks to _pyvcloud system.py_ which does not have ```create_vdc``` yet, so I guess it should be an issue in pyvcloud, right? ;-)

keep the good work!

**Comment by pacogomez** [comment]
see PR #139 and https://github.com/vmware/pyvcloud/pull/149

**Comment by flamby** [comment]
thanks, closing it then.
