### ISSUE TITLE
vcd-cli fails with API version: 31.0

### ISSUE THREAD

**Issue by fjmatos** [vmware/vcd-cli#254]
I´m testing  VCloud Director 9.5 GA + CSE 1.2.2 + vcd-cli 21.0.0

When I run:  $vcd cse system info , I get this error:

Error: Status code: 406/NOT_ACCEPTABLE, The request has invalid accept header: 
Unknown API version: 31.0. Supported API versions are:
 [5.5, 5.6, 5.7, 5.8, 5.9, 5.10, 5.11, 5.12, 6.0, 7.0, 9.0, 11.0, 12.0, 13.0, 14.0, 16.0, 17.0, 18.0, 19.0, 20.0,
 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0] (request id: df1782b0-7414-4566-ae54-3748dfb752c4)

So the API version 31.0 is not supported in this versión.
¿Is there a workaround to be able to use vcd cse with VCloud Director 9.5 ?

**Comment by rocknes** [comment]
Hi Javier,

I don't think you are using vcd-cli to talk to a 9.5 vCD. The list of supported api versions that's being displayed in the error message is sent to vcd-cli by vCD. And I don't see 31.0 listed in it, which leads me to believe that the vCD server in question is running vCD 9.1.

n.b. api version 31.0 was added in 9.5 release.

Regards
Aritra Sen

**Comment by fjmatos** [comment]
Thank you for your help rocknes.
The version of Vcloud Director  I got running is: 
VMware_vCloud_Director-9.5.0.3570-10266189_OVF10.ova
product.version = 9.5.0.10264774  , in global.properties.

**Comment by daydrim** [comment]
Hello, Have you found the solution ?
We have new error with the same versions of vCloud 9.5.0.10264774+ CSE 1.2.2 + vcd-cli 21.0.0

$ vcd cse system info
Usage: vcd cse system info [OPTIONS]
Try "vcd cse system info -h" for help.

Error: Cannot send message to service with id: xxxxxxxx-dddd-1111-aaaa-555955555999. Check your service configuration.

**Comment by fjmatos** [comment]
Hi daydrim.

I´ve found the solution for my case.

My problem was that I have a testbed with 2 environments

#1  VCloud Director 9.1+cse 1.1.0
#2  VCloud Director 9.5+cse 1.2.2

and both were connected to the same rabbitmq, using different extension but with the same namespace, so somehow vcd-cli connected to #2  was balancing the connection to #1.

I have created a new rabbitmq only for #2 and now vcd-cli is working fine  for me.

Your case looks a little bit different.  

Are you connected to your Vcloud director with vcd-cli and  using your vcloud administrator account ?

**Comment by daydrim** [comment]
Thank you. It seems that vCD-cli works correctly with api 31 and new rabbitmq
