### ISSUE TITLE
vca gateway del-ip not working 

### ISSUE THREAD

**Issue by ravisvi** [vmware/vcd-cli#26]
In file vcloudair.py
In line 1559 : org variable is reassigned to the gateway got from ctx.
In line 1570 : gateway, which will be of none type is used and not org, which is the gateway.

**Comment by ravisvi** [comment]
For now I can pass the gateway and avoid it.

**Comment by ravisvi** [comment]
However you can get it to work by passing the gateway explicitly.

**Comment by hodgesrm** [comment]
Obsolete code.
