### ISSUE TITLE
Can't login: list index out of range

### ISSUE THREAD

**Issue by ckamps** [vmware/vcd-cli#30]
vca_cli_version  14rc2
pyvcloud_version 14rc8  

When attempting to log into vCloud Director 5.5.x, receive the following error:

```
$ vca --debug --insecure login myuser --host my-url --org myorg --vdc myvdc --version 5.5
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.
Password:
User 'myuser' logged in, profile 'default'
Password encrypted and saved in local profile. Use --do-not-save-password to disable it.
Using VDC 'myvdc', profile 'default'
Can't login: list index out of range
```

However, when I use the same client and attempt to log into another vCloud Director environment, the login is successful.  The one in which the login fails is a substantially larger environment in all respects than the one in which login is successful.

BTW, I was unable to get the `--debug` option to work.  I had tried including both before and after the subcommand to no avail.

**Comment by abelyaevskiy** [comment]
Hi All! Do you have any updates on this? My collegue faced to the same issue and we did not find any solution.

**Comment by xcompass** [comment]
Got the same error. Was able to get around with manually adding VDC into ~/.vcarc
```
vdc=YOUR_VDC_NAMe
```
You can use vca status to check if the value is set.

**Comment by ckamps** [comment]
With the help of Yoram of Gigaspaces, we tracked down one cause of this error to the `pyvcloud` library assuming that at least one gateway always exists. In our case, we have zero gateways.

See the following section in `pyvcloud/vcloudair.py` where we added this line:

```python
if not link: return gateways
```
So that when `link` is empty, the ensuing code does not try to use it.

```python
def get_gateways(self, vdc_name):
    """
    Request a list of the Gateways within a Virtual Data Center.
 
    :param vdc_name: (str): The virtual data center name.
    :return: (list of Gateway)  A list of :class:`.pyvcloud.gateway.Gateway` objects describing the available gateways
 
    **service type:** ondemand, subscription, vcd
    """
    gateways = []
    vdc = self.get_vdc(vdc_name)
    if not vdc: return gateways
    link = filter(lambda link: link.get_rel() == "edgeGateways", vdc.get_Link())
    if not link: return gateways
    self.response = Http.get(link[0].get_href(), headers=self.vcloud_session.get_vcloud_headers(), verify=self.verify, logger=self.logger)
    if self.response.status_code == requests.codes.ok:
    ...
```
