### ISSUE TITLE
Add ability to create metadata on a VM

### ISSUE THREAD

**Issue by spengilley** [vmware/vcd-cli#322]
It would be wonderful to be able to use vcd-cli to create metadata on a VM.

**Comment by mikelitka** [comment]
This would be very helpful. We use interact programmatically with AWS tags and would like a comparable option here.

**Comment by pandeys** [comment]
This feature is already added. https://github.com/vmware/vcd-cli/pull/479. It is present in latest dev build of vcd-cli and pyvcloud. Once we do GA release, it can be accessed from GA build too..
