### ISSUE TITLE
vcd-cli command for removing snapshot on a VM is missing

### ISSUE THREAD

**Issue by swerveshot** [vmware/vcd-cli#495]
# Environment
Python 3.6.8
pyvcloud (21.0.0)
vcd-cli, VMware vCloud Director Command Line Interface, 22.0.0

# Proposed Functionality
Just as with vApps I'd like to have the ability to create, revert to and remove a snapshot of a specific VM. There is a PR #261 that implements this command. But it was never merged.

**Comment by pandeys** [comment]
These functionalities are available in current github code.

**Comment by swerveshot** [comment]
Thanks for your feedback @pandeys. Can you point me to the location please? Because I'm not able to find it in the repository.

**Comment by pandeys** [comment]
My bad. remove-snapshot is available in pyvcloud but not in vcd-cli. Create and revert to snapshot is there in vcd-cli. We will add remove-snaphot in code.

**Comment by swerveshot** [comment]
As long as pyvcloud has the appropriate function it's probably an easy task to implement this feature.

**Comment by pandeys** [comment]
remove-snapshot code is added.
