### ISSUE TITLE
Feature Request : Support for System login

### ISSUE THREAD

**Issue by flamby** [vmware/vcd-cli#55]
Hi,

Since vca-cli was used for VCA, it makes perfect sense that it was developed with Org scope in mind, w/ org-admin role at best, and thus not System account which is capable of listing all orgs, vdcs, edges, and so on.

Now that vca is gone, and VCD-SP is used extensively in SPs around the world, is it planned to target vca-cli usage for SP's administrators w/ System account login.

If i'm logging w/ my System account, it works like a charm, but I can't list organization for the reason mentionned above. Thus I can't do anything. The painful alternative afaik is to rely on an org-admin user on a per-org basis.

It would be great to be able to operate vcd in CLI w/ System account. My 2 cents.

Anyway, keep the good work!

**Comment by pacogomez** [comment]
Hi,

This is now supported in the new `vcd-cli`. It is under development and doesn't yet implement all the commands of the previous `vca-cli`, but we are quickly adding all the functionality and also the sys admin operations. Here is an example:

```
$ vcd login bos1-vcd-sp-static-199-4.eng.vmware.com System administrator -i -w
administrator logged in, org: 'System', vdc: ''

$ vcd org list
in_use    logged_in    name
--------  -----------  ------
False     False        org2
True      True         System
False     False        org1
```

See also [CSE](https://github.com/vmware/container-service-extension/wiki) for some of the sys admin commands

**Comment by flamby** [comment]
Hi Paco,

Thank you so much. I'll try it very soon.

Keep the good work!

**Comment by pacogomez** [comment]
closing now this issue as it is now fully supported. thanks for reporting.
