### ISSUE TITLE
Mac OS installation does not work

### ISSUE THREAD

**Issue by MrMorice** [vmware/vcd-cli#77]
After installing via "pip install --user vca-cli" the vca commant doesn't seem to be linked:

> $ vca
> vca: command not found

When installing with "pip install vca-cli" the following error is thrown:

> $ vca
> Traceback (most recent call last):
>   File "/usr/local/bin/vca", line 7, in <module>
>     from vca_cli.vca_cli import cli
>   File "/usr/local/lib/python2.7/site-packages/vca_cli/vca_cli.py", line 551, in <module>
>     import vca_cli_cluster  # NOQA
>   File "/usr/local/lib/python2.7/site-packages/vca_cli/vca_cli_cluster.py", line 17, in <module>
>     from pyvcloud.cluster import Cluster
> ImportError: No module named cluster

Mac OS 10.12.5 (16F73) Sierra
Python 2.7.13, pip 9.0.1

Thanks for your help!

All the best, MrMorice

**Comment by pacogomez** [comment]
please use `vcd-cli` module instead:

`pip install --user vcd-cli`

then you can run:

`vca --version`

and

`vcd version`

**Comment by pacogomez** [comment]
for the latest version, use:

`pip install --user vcd-cli --upgrade --pre`

**Comment by MrMorice** [comment]
Hi Paco!
thanks for the quick feedback. Still the --user argument wont let me start vcd but without it works perfectly. So I recommend:
> pip install vcd-cli --upgrade --pre

Best, MrMorice
