### ISSUE TITLE
Examples and Help

### ISSUE THREAD

**Issue by LEMNX** [vmware/vcd-cli#98]
Why did you get rid of the **Examples and Help** section in the read me?

That's your USP!

**Comment by pacogomez** [comment]
We have the documentation with examples here:

https://vmware.github.io/vcd-cli/

https://vmware.github.io/vcd-cli/commands.html

This is for the new `vcd-cli` implementation. We'll add more clear links in the readme.

**Comment by LEMNX** [comment]
OK, cool.
Thanks
